window.CNN_CROP_ID_LABELS = [
  "American Bollworm on Cotton",
  "Anthracnose on Cotton",
  "Army worm",
  "Brownspot",
  "Common_Rust",
  "Cotton Aphid",
  "Flag Smut",
  "Gray_Leaf_Spot",
  "Healthy Maize",
  "Healthy Wheat",
  "Healthy cotton",
  "Leaf Curl",
  "Leaf smut",
  "Mosaic sugarcane",
  "RedRot sugarcane",
  "RedRust sugarcane",
  "Rice Blast",
  "Sugarcane Healthy",
  "Tungro",
  "Wheat Brown leaf Rust",
  "Wheat Stem fly",
  "Wheat aphid",
  "Wheat black rust",
  "Wheat leaf blight",
  "Wheat mite",
  "Wheat powdery mildew",
  "Wheat scab",
  "Wheat___Yellow_Rust",
  "Wilt",
  "bacterial_blight_in_rice",
  "bacterial_blight_in_cotton",
  "bollworm on Cotton",
  "Unknown class 32",
  "Unknown class 33",
  "cotton mealy bug",
  "cotton whitefly",
  "maize ear rot",
  "maize fall armyworm",
  "maize stem borer",
  "pink bollworm in cotton",
  "red cotton bug",
  "thirps on  cotton"
];
